# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
#security:
#
#    encoders:
#        Symfony\Component\Security\User\User:
#            algorithm: bcrypt
#            cost:          13
#
#    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        in_memory:
#            memory:
#                users:
#                    admin:
#                        password: $2y$13$SoNRWA3YvTuZoVkrIGq1leIMcZFbYei2lnlh9oPA61dkCNr35jrxu
#                        #password: $2y$13$vwP.DdtLZ3ET1Rfn6Z1ub..fvP7JTGl2/SdggDsE5HA9BXpHCHb.K
#$2y$13$qgRdt6HMwuRqbVto5er7me1uVLPrlQm/xxfPb5BiI3/6qUfI0bFpq

#                        roles: [ 'ROLE_ADMIN' ]
#
#
#    firewalls:
#
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
#            # activate different ways to authenticate
#
#            # http_basic: ~
#            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
#
#            # form_login: ~
#            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
#
#
#        admin_secured_area:
#            pattern:      ^/admin/
#            http_basic:
#                realm:  "Secured Admin Area"
#
#    access_control:
#        - { path: ^/admin/, roles: ROLE_ADMIN }

security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      13

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$44iLeLBzr7tZJipkxrII6uSIo4sW7Hg2JOZLJjz7se2uyyzShYtwS
                        roles: [ 'ROLE_ADMIN' ]

    firewalls:
        admin_secured_area:
            pattern:    ^/admin/
            http_basic:
                realm: "Secured Admin Area"

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
